<!-- generated by SPLOT Comparator http://splot.ca/comparator -->

<!-- begin before/after placement -->

<div id="container">
<script>
if (typeof jQuery == 'undefined') {  
    // jQuery is not loaded, load it 

    var script = document.createElement('script');
    script.type = "text/javascript";
    script.src = "//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js";
    document.getElementsByTagName('head')[0].appendChild(script);

	// load jquery ui
    var script_ui = document.createElement('script');
    script_ui.type = "text/javascript";
    script_ui.src = "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js";
    document.getElementsByTagName('head')[0].appendChild(script_ui);

} else {
    // jQuery is loaded

    if (typeof jQuery.ui !== 'undefined') {
        // ui plugin exists
    } else {
        // ui plugin DOES NOT exist
        var script_ui = document.createElement('script');
        script_ui.type = "text/javascript";
        script_ui.src = "//ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.min.js";
        document.getElementsByTagName('head')[0].appendChild(script_ui);
    }
}
</script>

<?php

// just in case, put ID in for exisiting item
$default_cid = 12;

// get post id parameters from url string
$cid = (isset($_GET['cid'])) ? $_GET['cid'] : $default_cid;


// get the display option size
$compsize = get_post_meta( $cid, 'compsize', $single = true); 

// no size assigned, set one
if ( !$compsize) $compsize = 'small-landscape';


// get before and after images from post meta
$before_url = get_post_meta( $cid, 'before_img', $single = true); 								
$after_url = get_post_meta( $cid, 'after_img', $single = true); 

// add the file size name mods
// create the file name mods for the size chosen, the way wordpress
// adds -{width}x{width}.jpg
$file_size_name = '-' . $comp_size_options[$compsize][0] . 'x' . $comp_size_options[$compsize][1];
$before_url = str_replace('.jpg', $file_size_name . '.jpg', $before_url);
$after_url = str_replace('.jpg', $file_size_name . '.jpg', $after_url);
?>

<!-- load before/after	and UI touch punch for mobiles -->
	<script src="https://googledrive.com/host/0B3J3hv1B8VO1Vmh2R1U4UXBDVVk"></script>
	<script src="https://googledrive.com/host/0B3J3hv1B8VO1ZDluTEpLOGhhM0k"></script>
			
	<script type="text/javascript">
	$(window).load(function() {
		$('#container').beforeAfter({
			imagePath: "<?php echo get_stylesheet_directory_uri();?>/js/",
		});
		$('#container').draggable();
	});
	</script>


	<div><img alt="before" src="<?php echo $before_url?>" width="<?php echo $comp_size_options[$compsize][0]?>" height="<?php echo $comp_size_options[$compsize][1]?>" /></div>
	<div><img alt="after" src="<?php echo $after_url?>" width="<?php echo $comp_size_options[$compsize][0]?>" height="<?php echo $comp_size_options[$compsize][1]?>" /></div>
</div>
<!-- end before/after placement -->


